### ISSUE TITLE
requesting a way for ipumspy readers to read hierarchical extracts

### ISSUE THREAD

**Issue by swdrich** [ipums/ipumspy#64]
This is not an API function, but a way to read traditional extracts in hierarchical format.

**Comment by khwilson** [comment]
I'm not a big hierarchical extract user, so when I originally coded this up, I didn't have a good intuition for how hierarchical extracts should be parsed.

Do you have some examples of how you use hierarchical extracts that we might be able to crib a good dataframe layout from?

**Comment by franfabrizio** [comment]
I am not sure if this helps, but our ipumsr R client does support this, so
maybe the code samples we've published will help?
https://tech.popdata.org/ipumsr/articles/ipums.html?q=hierarchical#hierarchical-data-structures

**Comment by renae-r** [comment]
With version 0.3.0 of ipumspy (PR #86) hierarchical extracts may now be requested via the IPUMS API for available data collections and read into pandas using `readers.read_hierarchical_microdata()`.
