### ISSUE TITLE
Dependency `click` conflicts with common data science packages.

### ISSUE THREAD

**Issue by sondalex** [ipums/ipumspy#76]
- [x] Tested on last master branch commit
- [x] Tested on last pypi package version https://pypi.org/project/ipumspy/0.2.1/

----

Installation of `ipumspy` requires dependency `click<8.0.0,>=7.0.0`. This dependency conflicts with recent versions of [dtale](https://github.com/man-group/dtale), [jupyter-plotly](https://github.com/plotly/jupyter-dash) and maybe with other common data science packages.

It can be troublesome in data science virtual environments to fix this issue post installation.

Would it be possible to update [pyproject.toml](https://github.com/ipums/ipumspy/blob/01ce64bb27715021ae63f634412c266ba2db2e9a/pyproject.toml) ` click = "^7.0.0"` dependency to:

```console
[15] click = ">=7.0.0"
```

**Comment by renae-r** [comment]
These dependencies have finally been updated. Your problem should be fixed by installing from github or with `pip install ipumspy==0.2.2a0`. Sorry this took so long to address.
