### ISSUE TITLE
Typos in Python Documentation

### ISSUE THREAD

**Issue by rmcphersonCHPC** [ipums/ipumspy#78]
In the [Get Started documentation](https://ipumspy.readthedocs.io/en/latest/getting_started.html) for ipumspy, there is a typo in the DOWNLOAD_DIR variable:

`ddi_file = list(DOWLOAD_DIR.glob("*.xml"))[0]`

DOWNLOAD is missing the "N". 

Additionally, the two lines directly below should change "ipumsy" to "readers" as ipumsy does not work and readers is imported at the top of the documentation:
```
ddi = ipumspy.read_ipums_ddi(ddi_file)
ipums_df = ipumspy.read_microdata(ddi, DOWNLOAD_DIR / ddi.file_description.filename)
```
This will also make that block consistent with the code block in the **Read an IPUMS Extract** section.

**Comment by renae-r** [comment]
Thank you for bringing this issue to our attention! This issue has been resolved.
