### ISSUE TITLE
Unable to download with Python 3.11

### ISSUE THREAD

**Issue by ddav118** [ipums/ipumspy#79]
I am having issues downloading ipumspy and all of its associated dependencies with Python 3.11. Most of the required dependencies are outdated, including numpy which is seemingly giving me the most trouble. Any suggestions how I can resolve this conflict in dependencies?

**Comment by ddav118** [comment]
pyarrow version 3.0.0 is also giving me a lot of trouble to download. I am using Windows 11.

**Comment by renae-r** [comment]
Dependencies have been updated, but Python 3.11 is not officially supported yet. Please try downgrading to Python 3.10 and `pip install ipumspy==0.2.2a0`

**Comment by renae-r** [comment]
This issue is fixed with v0.3.0 of ipumspy (PR #86) . Thank you for your patience.
